version: "3"
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: app
    volumes:
      - ./:/app
    environment:
      - LOG_LEVEL
      - TZ=JST-9
    ports:
      - 8001:8001
    tty: true
